### ISSUE TITLE
Правки с тестирования (niyazm524)

### ISSUE THREAD

**Issue by niyazm524** [ani-team/github-client#164]
### Тестирование прошло гладко, в основном выявились небольшие замечания, как можно было бы улучшить проект, но ошибок нет:
![image](https://user-images.githubusercontent.com/32315145/100757400-63dc6f80-33ff-11eb-921c-bf99801d7502.png)

- [x] @niyazm524  [+3] Можно было бы добавить truncate на commit message, чтоб дата была видна всегда

------------------
![image](https://user-images.githubusercontent.com/32315145/100757593-9b4b1c00-33ff-11eb-9770-6508d6498e56.png)
- [x] @AdeliyaG [+2.5] Ссылки было бы неплохо сделать с target="_blank", то есть чтобы открывались в новой вкладке

------------------
-  ~~[-1.5] Также заметил, что при отсутствии соединения может показываться, что данных нет, но не выводится уведомление о том, что произошла ошибка, как по мне, не самое лучшее поведение~~

**Comment by martis-git** [comment]
Related #72

**Comment by martis-git** [comment]
> Также заметил, что при отсутствии соединения может показываться, что данных нет, но не выводится уведомление о том, что произошла ошибка, как по мне, не самое лучшее поведение

Согласен! Напишем нашему программисту, который это делал!)

**Comment by martis-git** [comment]
Эту вродь добили
