### ISSUE TITLE
Правки с код-ревью (niyazm524)

### ISSUE THREAD

**Issue by niyazm524** [ani-team/github-client#165]
- [x] @AdeliyaG [+1.5] Мы об этом уже говорили, что стили просятся в свою папку угодить
   <img src="https://user-images.githubusercontent.com/32315145/100758371-7e631880-3400-11eb-9c32-9a24355032a7.png" height=100 />

---------
- ~~[-1] Проект кишит тудушками и fixme, наверное это неплохо, но упомянуть стоит~~
   <img src="https://user-images.githubusercontent.com/32315145/100758747-e87bbd80-3400-11eb-9b72-f8557fe373e2.png" height=100 />

---------
- [x] @AdeliyaG [+3] Вынести бы в отдельную папку `hooks`
   <img src="https://user-images.githubusercontent.com/32315145/100759273-7f487a00-3401-11eb-9e13-8337ea316c97.png" height=100 />

---------
- [x] @niyazm524 [-0.5] Нет единого стиля объявления компонентов, то есть даже в одном файле может встретиться объявление через `function` и `const Component = (props) => {}`

--------
- ~~[-2.5] atomic-стили юзаются очень много где, боюсь, выпиливать их будет больновато~~
  <img src="https://user-images.githubusercontent.com/32315145/100760166-84f28f80-3402-11eb-89b1-8b77b4e1f3d2.png" height=10 />

--------
- ~~6..62. Остальное так или иначе указано в `!!! FIXME`~~

### В целом от кода приятные впечатления, по нему заметно, что было вложено много стараний

**Comment by martis-git** [comment]
Related #14
